<html>
    <head>
        <title>Lineup</title>
    </head>
    <body>
        <h1>ラインアップ</h1>
        <table>
        <tr><th>プロダクトID</th><th>シリーズID</th><th>カテゴリID</th></tr>
        </table>
    </body>
</html>
